### ISSUE TITLE
Clarify the semantics of the nbytes field for poll_oneoff

### ISSUE THREAD

**Issue by marmistrz** [WebAssembly/wasi-poll#6]
The semantics of this field in case of reading are quite clear for fds pointing to special devices such as sockets. Still, `poll` may be given a descriptor pointing to (a) a regular file (b) to a directory. Then, it's unclear:

* what's _the number of bytes available for reading or writing_ from a file descriptor pointing to a directory?
* what's _the number of bytes available for writing_ to a file descriptor pointing to a regular file? A sane answer could be the number of space available on the device, but it's probably something we don't want to leak.
* nitpicking: what's  _the number of bytes available for writing_ to a socket or stdin/stdout/stderr? A natural interpretation would be to say, what's the number of bytes available for writing so that the call doesn't block, but it doesn't follow from the spec.

**Comment by sunfishcode** [comment]
This was a feature WASI got from CloudABI's `poll` syscall. It roughly corresponds to calling the Unix-family `FIONREAD` ioctl after `poll` returns, however that ioctl itself also has a fairly unclear meaning.

In WASI Preview2, this poll function is being subsumed by the component-model `wait` function. It does not currently have any feature corresponding to this `nbytes` field. It doesn't appear to be widely used. If we do discover important uses for it, I expect we can add new features to the component model, such as a variant of listen/read that returns an event that contains how many bytes can be read without blocking. That would likely still need to be implemented by `FIONREAD`, which would be an additional system call, which would be overhead that not all use cases would need, so it makes sense for it to be a separate function rather than adding this to the main listen/read function.
